#!/usr/bin/env python3
"""Generate the snd-clarett ALSA UCM profiles (ucm2/Clarett/Clarett-<model>-HiFi.conf) for the
Clarett 8Pre and 8PreX.

Each profile splits the model's playback and capture PCM into named devices for desktop sound
settings. Structure follows the Focusrite Scarlett configs in alsa-ucm-conf (4th Gen where they
differ); names follow alsa-scarlett-gui's Routing page for the model, with plain hyphens for its en
dashes; capture devices are named after the hardware input that feeds them, except the loopback pair,
which keeps "Loopback 1-2". Channel layouts come from the vendor descriptors (record-outputs order,
outputs) and the driver's GET_7.1 channel counts.

The 2Pre and 4Pre profiles are hand-written (different output layouts) and are not produced here.
ucm2/Clarett/Clarett.conf, which picks a profile by card name, is hand-written too.

Usage: tools/gen_ucm.py [MODEL ...]     (default: every model below; writes into snd-clarett/ucm2/Clarett)
"""
import os
import sys

def macro(name, direction, ch, hw, pos):
    lines = [f'\t{{\n\t\tSplitPCM {{\n\t\t\tName "{name}"\n\t\t\tDirection {direction}\n\t\t\tFormat S32_LE\n'
             f'\t\t\tChannels {ch}\n\t\t\tHWChannels {hw}']
    lines += [f'\t\t\tHWChannelPos{i} {pos(i)}' for i in range(hw)]
    return '\n'.join(lines) + '\n\t\t}\n\t}'

def device(dev_id, comment, prio_key, prio, pcm, direction, hw, chans, pos, note=None):
    out = [f'SectionDevice."{dev_id}" {{']
    if note:
        out.append(f'\t# {note}')
    out += [f'\tComment "{comment}"', '', '\tValue {', f'\t\t{prio_key} {prio}', '\t}', '',
            '\tMacro.pcm_split.SplitPCMDevice {', f'\t\tName "{pcm}"', f'\t\tDirection {direction}',
            f'\t\tHWChannels {hw}', f'\t\tChannels {len(chans)}']
    out += [f'\t\tChannel{i} {c}' for i, c in enumerate(chans)]
    out += [f'\t\tChannelPos{i} {pos[i]}' for i in range(len(chans))]
    out += ['\t}', '}', '']
    return '\n'.join(out)

STEREO = ['FL', 'FR']
ADATPOS = ['UNKNOWN'] * 8

def build(m):
    p, c, key = m['play'], m['cap'], m['key']
    so, mi, si, ai = f'{key}_stereo_out', f'{key}_mono_in', f'{key}_stereo_in', f'{key}_adat_in'
    ao = f'{key}_adat_out'
    s = [m['header'], 'Include.pcm_split.File "/common/pcm/split.conf"', '', 'Macro [']
    s.append('\n'.join([
        macro(so, 'Playback', 2, p, lambda i: STEREO[i % 2]),
        macro(ao, 'Playback', 8, p, lambda i: 'UNKNOWN'),
        macro(mi, 'Capture', 1, c, lambda i: 'MONO'),
        macro(si, 'Capture', 2, c, lambda i: STEREO[i % 2]),
        macro(ai, 'Capture', 8, c, lambda i: 'UNKNOWN')]))
    s += [']', '']
    s.append('# Analogue Outputs\n')
    prio = 200
    for i, (dev, name, first) in enumerate(m['outs']):
        s.append(device(dev, name, 'PlaybackPriority', prio, so, 'Playback', p, [first, first + 1], STEREO,
                        note=m.get('notes', {}).get(dev)))
        prio -= 10
    s.append('# Digital (Consumer) Outputs\n')
    s.append(device('SPDIF1', 'S/PDIF 1-2', 'PlaybackPriority', 112, so, 'Playback', p,
                    [m['spdif_out'], m['spdif_out'] + 1], STEREO))
    s.append('# Digital (Professional) Outputs\n')
    for i, (name, first) in enumerate(m['adat_out']):
        s.append(device(f'Direct{i + 1}', name, 'PlaybackPriority', 48 - i, ao, 'Playback', p,
                        list(range(first, first + 8)), ADATPOS))
    s.append('# Analogue Inputs\n')
    cprio = [500, 400] + [390 - 10 * i for i in range(6)]
    for i, (dev, name) in enumerate(m['ins']):
        s.append(device(dev, name, 'CapturePriority', cprio[i], mi, 'Capture', c, [i], ['MONO']))
    s.append('# Loopback Inputs\n')
    s.append(device(m['loop_dev'], 'Loopback 1-2', 'CapturePriority', 300, si, 'Capture', c,
                    [m['loop'], m['loop'] + 1], STEREO))
    s.append('# Digital (Consumer) Inputs\n')
    for i in range(2):
        s.append(device(f'SPDIF{i + 2}', f'S/PDIF {i + 1}', 'CapturePriority', 112 - i, mi, 'Capture', c,
                        [m['spdif_in'] + i], ['MONO']))
    s.append('# Digital (Professional) Inputs\n')
    n = len(m['adat_out'])
    for i, (name, first) in enumerate(m['adat_in']):
        s.append(device(f'Direct{n + i + 1}', name, 'CapturePriority', 48 - i, ai, 'Capture', c,
                        list(range(first, first + 8)), ADATPOS))
    return '\n'.join(s).rstrip('\n') + '\n'

INS = [('Mic1', 'Mic/Line/Inst 1'), ('Mic2', 'Mic/Line/Inst 2')] + \
      [(f'Mic{i}', f'Mic/Line {i}') for i in range(3, 9)]
OUTS = [('Line1', 'Line 1-2', 0), ('Line2', 'Line 3-4', 2), ('Line3', 'Line 5-6', 4),
        ('Line4', 'Line 7-8/Headphones 1', 6), ('Line5', 'Line 9-10/Headphones 2', 8)]

def header(model, play, cap, extra_out, extra_cap, loop_pcm, cap_end):
    return f"""# Generated by tools/gen_ucm.py in the clarett-sre project: change the
# generator, not this file.
#
# Clarett {model}: split the {play}-channel playback and {cap}-channel capture PCM into
# named devices. The device structure follows the upstream Focusrite Scarlett
# configs (4th Gen where they differ); the names follow alsa-scarlett-gui's
# Routing page for this model, so the desktop and the router agree, with plain
# hyphens for its en dashes (no UCM config uses an en dash). Capture devices
# take the name of the hardware input that feeds them.
#
# Playback channels (router PCM sources) and the output each one maps to
# one-to-one; names follow the device's own jack labels:
#
#   ch 0-1    Monitor Output 1-2
#   ch 2-5    Line Output 3-6
#   ch 6-7    Line Output 7-8, mirrored on headphone output 1
#   ch 8-9    Line Output 9-10, mirrored on headphone output 2
#   ch 10-11  S/PDIF Output 1-2
{extra_out}
#
# Capture channel order is the hardware's record block (pins 0x600-{cap_end}):
#
#   ch 0-7    Analogue 1-8 (1-2 Mic/Line/Inst, 3-8 Mic/Line)
#   ch 8-9    S/PDIF 1-2
#   ch 10-11  Loopback 1-2 (the Routing page calls these {loop_pcm}; named
#             "Loopback" here because no physical input feeds them)
{extra_cap}
#
# Like upstream, the names describe that one-to-one correspondence; the router
# can send any of these channels elsewhere. ADAT devices keep their full width
# at every rate (UCM cannot follow the sample rate; S/MUX carries 4 or 2
# channels per port at double or quad speed).
"""

MODELS = {
    '8Pre': dict(key='clarett8pre', play=20, cap=20, outs=OUTS, spdif_out=10,
                 adat_out=[('ADAT 1-8', 12)], ins=INS, loop=10, loop_dev='Line6', spdif_in=8,
                 adat_in=[('ADAT 1-8', 12)],
                 header=header('8Pre', 20, 20, '#   ch 12-19  ADAT Output 1-8',
                               '#   ch 12-19  ADAT 1-8', 'PCM 19-20', '0x613')),
    '8PreX': dict(key='clarett8prex', play=28, cap=28, outs=OUTS, spdif_out=10,
                  adat_out=[('ADAT 1-8', 12), ('ADAT 9-16', 20)], ins=INS, loop=10, loop_dev='Line6',
                  spdif_in=8, adat_in=[('ADAT 1-8', 12), ('ADAT 9-16', 20)],
                  header=header('8PreX', 28, 28,
                                '#   ch 12-19  ADAT Output 1-8 (port 1)\n#   ch 20-27  ADAT Output 9-16 (port 2)',
                                '#   ch 12-19  ADAT 1-8 (port 1)\n#   ch 20-27  ADAT 9-16 (port 2)',
                                'PCM 27-28', '0x61b')),
}

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'snd-clarett', 'ucm2', 'Clarett')

if __name__ == '__main__':
    models = sys.argv[1:] or list(MODELS)
    for model in models:
        if model not in MODELS:
            sys.exit(f'unknown model {model!r}; known: {", ".join(MODELS)}')
        path = os.path.normpath(os.path.join(OUT_DIR, f'Clarett-{model}-HiFi.conf'))
        with open(path, 'w') as f:
            f.write(build(MODELS[model]))
        print(path)
